### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by paf31** [joneshf/purescript-node-url#1]
@joneshf I didn't realize this library existed until I just tried to `bower register` my own just now:

https://github.com/purescript-node/purescript-node-url

Do you have plans to update this library? Would you like to merge the two?

**Comment by joneshf** [comment]
If you'd like, I can unregister the name so you can use it, or transfer it, or whatever you have to do with bower.

**Comment by cstrahan** [comment]
Just tried pulling down `purescript-node-url`, and then realized (after it failed to compile with the latest `psc`) that the bower component was registered here, rather than https://github.com/purescript-node/purescript-node-url.

@joneshf Would you mind transferring over the name to @paf31 et al?

**Comment by joneshf** [comment]
@cstrahan that's entirely up to @paf31. I don't want to stick him with the name if he doesn't want it, but as I said above, I'm more than willing to transfer it over or whatever.

**Comment by paf31** [comment]
I'm happy to take over the name, I don't mind.

**Comment by joneshf** [comment]
Just unregistered. Have at it!
